--[[ vfbs.Member

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Member = {}
local mt = {}

function Member.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:KeyType()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function mt:Key()
  local o = self.view:Offset(6)
  if o ~= 0 then
   local obj = flatbuffers.view.New(flatbuffers.binaryArray.New(0), 0)
    self.view:Union(obj, o)
    return obj
  end
end

function mt:ValueType()
  local o = self.view:Offset(8)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Uint8, self.view.pos + o)
  end
  return 0
end

function mt:Value()
  local o = self.view:Offset(10)
  if o ~= 0 then
   local obj = flatbuffers.view.New(flatbuffers.binaryArray.New(0), 0)
    self.view:Union(obj, o)
    return obj
  end
end

function Member.Start(builder)
  builder:StartObject(4)
end

function Member.AddKeyType(builder, keyType)
  builder:PrependUint8Slot(0, keyType, 0)
end

function Member.AddKey(builder, key)
  builder:PrependUOffsetTRelativeSlot(1, key, 0)
end

function Member.AddValueType(builder, valueType)
  builder:PrependUint8Slot(2, valueType, 0)
end

function Member.AddValue(builder, value)
  builder:PrependUOffsetTRelativeSlot(3, value, 0)
end

function Member.End(builder)
  return builder:EndObject()
end

return Member