--[[ vfbs.Tbool

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Tbool = {}
local mt = {}

function Tbool.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Value()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return (self.view:Get(flatbuffers.N.Bool, self.view.pos + o) ~=0)
  end
  return false
end

function Tbool.Start(builder)
  builder:StartObject(1)
end

function Tbool.AddValue(builder, value)
  builder:PrependBoolSlot(0, value, false)
end

function Tbool.End(builder)
  return builder:EndObject()
end

return Tbool