--[[ vfbs.Tclass

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local __vfbs_Member = require('vfbs.Member')
local flatbuffers = require('flatbuffers')

local Tclass = {}
local mt = {}

function Tclass.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function Tclass.GetRootAsTclass(buf, offset)
  if type(buf) == "string" then
    buf = flatbuffers.binaryArray.New(buf)
  end

  local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
  local o = Tclass.New()
  o:Init(buf, n + offset)
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Members(j)
  local o = self.view:Offset(4)
  if o ~= 0 then
    local x = self.view:Vector(o)
    x = x + ((j-1) * 4)
    x = self.view:Indirect(x)
    local obj = __vfbs_Member.New()
    obj:Init(self.view.bytes, x)
    return obj
  end
end

function mt:MembersLength()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function Tclass.Start(builder)
  builder:StartObject(1)
end

function Tclass.AddMembers(builder, members)
  builder:PrependUOffsetTRelativeSlot(0, members, 0)
end

function Tclass.StartMembersVector(builder, numElems)
  return builder:StartVector(4, numElems, 4)
end

function Tclass.End(builder)
  return builder:EndObject()
end

return Tclass