--[[ vfbs.Tdouble

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Tdouble = {}
local mt = {}

function Tdouble.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Value()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Float64, self.view.pos + o)
  end
  return 0.0
end

function Tdouble.Start(builder)
  builder:StartObject(1)
end

function Tdouble.AddValue(builder, value)
  builder:PrependFloat64Slot(0, value, 0.0)
end

function Tdouble.End(builder)
  return builder:EndObject()
end

return Tdouble