--[[ vfbs.Tint64

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Tint64 = {}
local mt = {}

function Tint64.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Value()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int64, self.view.pos + o)
  end
  return 0
end

function Tint64.Start(builder)
  builder:StartObject(1)
end

function Tint64.AddValue(builder, value)
  builder:PrependInt64Slot(0, value, 0)
end

function Tint64.End(builder)
  return builder:EndObject()
end

return Tint64