--[[ vfbs.Tnative

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Tnative = {}
local mt = {}

function Tnative.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function mt:Factor()
  local o = self.view:Offset(4)
  if o ~= 0 then
    return self.view:Get(flatbuffers.N.Int32, self.view.pos + o)
  end
  return 0
end

function mt:Value(j)
  local o = self.view:Offset(6)
  if o ~= 0 then
    local a = self.view:Vector(o)
    return self.view:Get(flatbuffers.N.Uint8, a + ((j-1) * 1))
  end
  return 0
end

function mt:ValueAsString(start, stop)
  return self.view:VectorAsString(6, start, stop)
end

function mt:ValueLength()
  local o = self.view:Offset(6)
  if o ~= 0 then
    return self.view:VectorLen(o)
  end
  return 0
end

function Tnative.Start(builder)
  builder:StartObject(2)
end

function Tnative.AddFactor(builder, factor)
  builder:PrependInt32Slot(0, factor, 0)
end

function Tnative.AddValue(builder, value)
  builder:PrependUOffsetTRelativeSlot(1, value, 0)
end

function Tnative.StartValueVector(builder, numElems)
  return builder:StartVector(1, numElems, 1)
end

function Tnative.End(builder)
  return builder:EndObject()
end

return Tnative