--[[ vfbs.Tnull

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local flatbuffers = require('flatbuffers')

local Tnull = {}
local mt = {}

function Tnull.New()
  local o = {}
  setmetatable(o, {__index = mt})
  return o
end

function mt:Init(buf, pos)
  self.view = flatbuffers.view.New(buf, pos)
end

function Tnull.Start(builder)
  builder:StartObject(0)
end

function Tnull.End(builder)
  return builder:EndObject()
end

return Tnull