--[[ vfbs.Type

  Automatically generated by the FlatBuffers compiler, do not modify.
  Or modify. I'm a message, not a cop.

  flatc version: 22.9.29

  Declared by  : //generic.fbs
  Rooting type : vfbs.TClass (//generic.fbs)

--]]

local Type = {
  NONE = 0,
  TNull = 1,
  TBool = 2,
  TShort = 3,
  TUShort = 4,
  TInt = 5,
  TUInt = 6,
  TFloat = 7,
  TDouble = 8,
  TString = 9,
  TNative = 10,
  TClass = 11,
  TInt64 = 12,
  TUInt64 = 13,
  TRefrence = 14,
}

return Type